name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - 'dev'

permissions:
  contents: write

jobs:
  cicd:
    name: Continuously intergrate to dev branch
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install node packages
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Deploy to gh-io branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout gh-io branch
        run: |
          git fetch origin gh-io || git checkout --orphan gh-io
          git checkout gh-io

      - name: Remove all files except .git
        run: find . -mindepth 1 -maxdepth 1 ! -name 'dist' ! -name '.git' -exec rm -rf {} +

      - name: Copy only necessary files from dist/
        run: |
          mv dist/* .
          rm -rf dist

      - name: Add and commit changes
        run: |        
          git add .
          git commit -am "Deploy built files to gh-io branch" || echo "No changes to commit"
          git push origin gh-io
  
